### ISSUE TITLE
node_modules.zip存放的必要性

### ISSUE THREAD

**Issue by gadfly3173** [youlaitech/mall-admin#2]
node_modules中的文件与package-lock.json和本机node版本以及系统密切相关，切换node版本或者系统都可能导致其不可用，且依赖包体积过大，没什么必要放在GitHub中

**Comment by hxrui** [comment]
收到，今晚回去整理下，因为之前有人环境安装依赖时github有问题，所以放在gitee上的，后同步更新到github上了

**Comment by hxrui** [comment]
> node_modules中的文件与package-lock.json和本机node版本以及系统密切相关，切换node版本或者系统都可能导致其不可用，且依赖包体积过大，没什么必要放在GitHub中

收到，今晚回去整理下，因为之前有人环境安装依赖时github有问题，所以放在gitee上的，后同步更新到github上了
